# -*- coding: utf-8 -*-
# Conteudo das paginas de servico. Fatos sobre a Scherr limitados ao que ja consta no site.

PAGES = [
{
 "slug": "tratamento-de-agua-de-caldeiras",
 "frase": "tratamento de água de caldeiras",
 "icon": "flame",
 "nav": "Caldeiras",
 "title": "Tratamento de Água de Caldeiras e Geradores de Vapor | Scherr",
 "desc": "Produtos químicos e assistência técnica para tratamento de água de caldeiras: tratamento externo, interno e da rede de vapor condensado. Scherr Química, MG.",
 "h1": "Tratamento de água de caldeiras e geradores de vapor",
 "lead": "Produtos químicos e assistência técnica para o ciclo completo da água de caldeiras — tratamento externo, tratamento interno e proteção da rede de vapor e condensado — com foco em eficiência térmica, economia de combustível e vida útil do equipamento.",
 "service_name": "Tratamento de água de geradores de vapor (caldeiras)",
 "img": "about-industrial-valves.jpg",
 "img_alt": "Válvulas e tubulação de rede de vapor industrial",
 "problem_h2": "O que acontece com uma caldeira sem tratamento de água adequado",
 "problem_p": "A água de alimentação carrega sais dissolvidos, oxigênio e gases que, sob temperatura e pressão, se concentram no interior do gerador de vapor. Sem um programa químico consistente, três mecanismos de degradação atuam ao mesmo tempo e se realimentam.",
 "problem_items": [
   ("Incrustação", "Sais de cálcio e magnésio precipitam nas superfícies de troca térmica e formam depósitos isolantes. Uma camada fina de incrustação já é suficiente para elevar a temperatura do metal e aumentar o consumo de combustível para produzir o mesmo vapor."),
   ("Corrosão", "O oxigênio dissolvido e o gás carbônico atacam o aço do costado, dos tubos e, principalmente, da linha de condensado. A corrosão por pite é localizada e pode perfurar tubos sem aviso prévio."),
   ("Arraste e contaminação do vapor", "Sólidos dissolvidos em excesso e alcalinidade fora de faixa provocam arraste de água junto com o vapor, o que contamina o processo e danifica linhas, purgadores e trocadores a jusante."),
   ("Fragilização e superaquecimento", "Depósitos localizados criam pontos quentes. O metal superaquecido perde resistência mecânica, o que é a origem mais comum de falhas graves em tubos de caldeira."),
 ],
 "how_h2": "Como estruturamos o tratamento",
 "how_items": [
   ("Tratamento externo da água de alimentação", "Condicionamento da água antes da entrada na caldeira: abrandamento, desmineralização e remoção de dureza, sílica e matéria orgânica conforme a pressão de operação e a qualidade da água bruta disponível."),
   ("Tratamento interno", "Dosagem de produtos químicos no interior do gerador de vapor para controlar dureza residual, sequestrar o oxigênio dissolvido, ajustar alcalinidade e pH e dispersar sólidos, mantendo-os em suspensão para remoção pelas descargas."),
   ("Rede de vapor e condensado", "Proteção das linhas de retorno contra corrosão ácida por CO₂ e por oxigênio, preservando o condensado — que é água quente e de baixa condutividade, e portanto o insumo mais valioso do ciclo."),
   ("Controle analítico e ajuste de regime", "Definição das faixas de controle, rotina de análises, regime de descargas de fundo e de superfície e ajuste da dosagem conforme a carga real da caldeira."),
 ],
 "prod_h2": "Linha de produtos aplicada em geradores de vapor",
 "prod_items": [
   "Sequestrantes de oxigênio para eliminação do oxigênio dissolvido residual",
   "Inibidores de incrustação e condicionadores de lama para dureza residual",
   "Alcalinizantes e produtos para controle de pH da água da caldeira",
   "Aminas neutralizantes e filmantes para proteção da rede de vapor e condensado",
   "Dispersantes para manutenção dos sólidos em suspensão",
   "Produtos para limpeza química de pré-operação e de manutenção",
 ],
 "results_items": [
   ("Economia de combustível", "Superfícies de troca térmica limpas transferem calor com a eficiência de projeto, reduzindo o consumo por tonelada de vapor produzida."),
   ("Menos paradas não programadas", "Controle de corrosão e de depósitos reduz falhas de tubo e a necessidade de intervenções emergenciais."),
   ("Vida útil do equipamento", "Preservação do costado, dos tubos e da rede de condensado ao longo dos anos."),
   ("Rastreabilidade", "Relatórios periódicos de avaliação do tratamento, com histórico das análises e das inspeções realizadas."),
 ],
 "faq": [
   ("Com que frequência a água da caldeira deve ser analisada?",
    "A frequência depende da pressão de operação, da carga e da estabilidade da água de alimentação. Caldeiras industriais em operação contínua costumam exigir controle diário dos parâmetros básicos — pH, alcalinidade, condutividade, dureza e teor de sequestrante de oxigênio — complementado por análises laboratoriais mais completas em intervalos maiores. Definimos a rotina caso a caso e emitimos relatórios periódicos de avaliação do tratamento."),
   ("Tratamento de água de caldeira substitui a limpeza química?",
    "Não. O tratamento químico contínuo evita a formação de novos depósitos, mas não remove incrustação já consolidada. Quando a caldeira chega ao programa com histórico de depósito, a limpeza química é a etapa que devolve a superfície de troca ao estado limpo; o tratamento contínuo é o que mantém esse estado. A Scherr executa limpezas químicas em geradores de vapor, trocadores de calor e tubulações."),
   ("Por que o retorno de condensado precisa de tratamento próprio?",
    "O condensado é água praticamente pura e quente, o que o torna o insumo mais econômico do ciclo — mas também agressivo. O gás carbônico liberado na caldeira acompanha o vapor e, ao condensar, forma ácido carbônico, que corrói as linhas de retorno. Sem proteção específica, o condensado chega contaminado com produtos de corrosão e acaba sendo descartado, o que desperdiça água e energia."),
   ("A Scherr fornece os equipamentos de dosagem?",
    "Sim. Tanques de dosagem, tanques de estocagem, bombas dosadoras, drenos e descargas automáticas podem ser fornecidos em regime de comodato. Também realizamos a montagem de laboratório com infraestrutura, aparelhagem e analista."),
 ],
},
{
 "slug": "tratamento-de-agua-de-torres-de-resfriamento",
 "frase": "tratamento de água de torres de resfriamento",
 "icon": "droplets",
 "nav": "Torres de resfriamento",
 "title": "Tratamento de Água de Torres de Resfriamento | Scherr Química",
 "desc": "Produtos químicos para torres de resfriamento e água clarificada: controle de incrustação, corrosão e microbiologia, com maximização dos ciclos de concentração.",
 "h1": "Tratamento de água de torres de resfriamento",
 "lead": "Programas químicos para circuitos abertos de resfriamento e água clarificada, com controle simultâneo de incrustação, corrosão e crescimento microbiológico — e maximização dos ciclos de concentração para reduzir consumo de água e de purga.",
 "service_name": "Tratamento de água de torres de resfriamento",
 "img": "partners-water-drop.jpg",
 "img_alt": "Gota d'água formando ondulações na superfície",
 "problem_h2": "Os três problemas simultâneos de um circuito aberto",
 "problem_p": "Uma torre de resfriamento evapora água para retirar calor. A cada ciclo, os sais dissolvidos ficam para trás e se concentram, enquanto a bacia aberta recebe luz, ar, poeira e matéria orgânica. O resultado é um sistema que sofre três ataques ao mesmo tempo, e cujo tratamento precisa equilibrar os três — porque o que resolve um tende a agravar o outro.",
 "problem_items": [
   ("Incrustação", "A concentração progressiva de cálcio, magnésio e sílica leva à saturação e à precipitação sobre as superfícies de troca dos trocadores e condensadores, reduzindo o coeficiente de troca térmica."),
   ("Corrosão", "Água aerada, com sólidos dissolvidos e cloretos concentrados, ataca o aço carbono, as ligas de cobre e o admiralty presentes nos trocadores. A corrosão sob depósito é a forma mais destrutiva."),
   ("Crescimento microbiológico", "Bacia aberta, temperatura amena e nutrientes favorecem bactérias, fungos e algas. O biofilme resultante é isolante térmico, acelera a corrosão localizada e obstrui o enchimento da torre."),
   ("Fouling por sólidos suspensos", "Poeira e material particulado arrastados do ar depositam-se em pontos de baixa velocidade e servem de abrigo para o biofilme."),
 ],
 "how_h2": "Como estruturamos o tratamento",
 "how_items": [
   ("Diagnóstico do circuito e da água de reposição", "Levantamento da qualidade da água de reposição, dos materiais presentes no circuito, das temperaturas de pele e do balanço de massa da torre. É esse levantamento que define o ciclo de concentração viável."),
   ("Programa de inibição de incrustação e corrosão", "Seleção de inibidores compatíveis com as ligas presentes e com a química da água, mantendo o índice de saturação sob controle sem exigir purga excessiva."),
   ("Controle microbiológico", "Programa de biocidas oxidantes e não oxidantes, com alternância planejada para evitar seleção de população resistente, e controle de biofilme."),
   ("Maximização dos ciclos de concentração", "Elevar o ciclo com segurança reduz diretamente a água de reposição e o volume de purga descartado. É onde está o maior ganho econômico e ambiental do programa."),
   ("Monitoramento com corpos de prova", "Determinação das taxas de corrosão e deposição em corpos de prova de aço carbono, ligas de cobre e admiralty, com registro fotográfico."),
 ],
 "prod_h2": "Linha de produtos aplicada em sistemas de resfriamento",
 "prod_items": [
   "Inibidores de incrustação e dispersantes para controle de depósitos",
   "Inibidores de corrosão para aço carbono e para ligas de cobre e admiralty",
   "Biocidas oxidantes e não oxidantes para controle microbiológico",
   "Biodispersantes para remoção e prevenção de biofilme",
   "Produtos para controle de pH e alcalinidade do circuito",
   "Coagulantes e auxiliares para tratamento de água clarificada",
 ],
 "results_items": [
   ("Troca térmica preservada", "Trocadores e condensadores operando próximos ao coeficiente de projeto, o que sustenta a capacidade de produção nos dias mais quentes."),
   ("Menos água e menos purga", "Ciclos de concentração mais altos reduzem a reposição e o volume enviado ao descarte."),
   ("Proteção dos metais do circuito", "Taxas de corrosão acompanhadas por corpos de prova, com evidência documentada em vez de estimativa."),
   ("Controle microbiológico documentado", "Contagem microbiológica periódica e histórico de resultados."),
 ],
 "faq": [
   ("O que são ciclos de concentração e por que aumentá-los?",
    "O ciclo de concentração é a razão entre a concentração de sais na água do circuito e na água de reposição. Um ciclo maior significa que a mesma água foi reutilizada mais vezes antes de ser purgada — ou seja, menos água captada e menos efluente gerado. O limite é químico: acima de certo ponto os sais saturam e precipitam. Um programa de inibição bem dimensionado é justamente o que permite operar em ciclo alto sem incrustar."),
   ("Como se controla a Legionella e o risco microbiológico em torres?",
    "Torres de resfriamento são sistemas abertos que geram aerossóis, e o controle microbiológico é uma questão de segurança além de operacional. O controle se dá pela combinação de programa de biocidas com alternância planejada, controle de biofilme, limpeza periódica da bacia e do enchimento, e monitoramento por contagem microbiológica. A Scherr realiza contagem microbiológica e emite relatórios periódicos."),
   ("Vocês monitoram a corrosão de forma objetiva?",
    "Sim. Instalamos corpos de prova de aço carbono, ligas de cobre e admiralty no circuito e determinamos as taxas de corrosão e de deposição por perda de massa, com registro fotográfico. Isso substitui a avaliação subjetiva por um número comparável ao longo do tempo."),
   ("O tratamento serve para circuitos de água clarificada?",
    "Sim. O tratamento de água clarificada segue a mesma lógica de controle de incrustação, corrosão e microbiologia, ajustada à qualidade da água disponível e ao uso no processo."),
 ],
},
{
 "slug": "tratamento-de-efluentes-industriais",
 "frase": "tratamento de efluentes industriais",
 "icon": "recycle",
 "nav": "Efluentes",
 "title": "Tratamento de Efluentes Industriais | Produtos Químicos | Scherr",
 "desc": "Coagulantes, floculantes e polímeros para tratamento físico-químico de efluentes industriais, com monitoramento operacional e químico da estação.",
 "h1": "Tratamento de efluentes industriais",
 "lead": "Coagulantes, floculantes e polímeros para tratamento físico-químico de efluentes industriais, acompanhados do monitoramento operacional e químico da estação — para enquadramento no padrão de lançamento e redução do volume de lodo gerado.",
 "service_name": "Tratamento de efluentes industriais",
 "img": "hero-water-treatment.jpg",
 "img_alt": "Vista aérea dos tanques de uma estação de tratamento",
 "problem_h2": "Por que o tratamento físico-químico exige ajuste contínuo",
 "problem_p": "Efluente industrial não tem composição constante. Mudanças de campanha, de matéria-prima, de turno ou de chuva alteram vazão, pH, carga orgânica e sólidos suspensos. Uma dosagem fixa que funcionou no mês passado pode gerar, hoje, efluente fora do padrão ou consumo desnecessário de produto.",
 "problem_items": [
   ("Enquadramento no padrão de lançamento", "Parâmetros fora da faixa exigida pelo órgão ambiental expõem a operação a autuação e a interrupção de licença."),
   ("Volume e desaguamento do lodo", "Coagulação e floculação mal ajustadas produzem lodo em excesso e com baixa desidratabilidade, o que eleva o custo de destinação."),
   ("Variabilidade de carga", "Picos de carga orgânica ou de sólidos desestabilizam a estação e comprometem o resultado do decantador."),
   ("Custo de produto químico", "Sobredosagem é um custo silencioso e recorrente, e frequentemente piora o resultado em vez de melhorá-lo."),
 ],
 "how_h2": "Como estruturamos o tratamento",
 "how_items": [
   ("Caracterização do efluente", "Análise da água a ser tratada e ensaios de bancada (jar test) para definir o coagulante, o polímero e as faixas de pH e de dosagem que dão o melhor resultado para aquele efluente."),
   ("Seleção do programa químico", "Definição da linha de coagulantes, floculantes e auxiliares adequada à natureza do efluente e ao tipo de estação instalada."),
   ("Ajuste operacional da estação", "Acompanhamento dos pontos de dosagem, dos tempos de mistura e de floculação e do regime do decantador — o resultado depende tanto da operação quanto do produto."),
   ("Monitoramento operacional e químico", "Monitoramento das estações de efluentes em nível operacional e químico, com relatórios periódicos e inspeções com registro fotográfico."),
 ],
 "prod_h2": "Linha de produtos aplicada em efluentes",
 "prod_items": [
   "Coagulantes inorgânicos e orgânicos para desestabilização de coloides",
   "Floculantes poliméricos aniônicos, catiônicos e não iônicos",
   "Polímeros para desaguamento e adensamento de lodo",
   "Produtos para correção de pH e alcalinidade",
   "Auxiliares de clarificação e antiespumantes",
   "Produtos para controle de odor e de sulfetos",
 ],
 "results_items": [
   ("Efluente dentro do padrão", "Parâmetros de lançamento estabilizados e documentados em relatório."),
   ("Menos lodo para destinar", "Programa ajustado gera lodo em menor volume e com melhor desidratabilidade."),
   ("Dosagem sob controle", "Consumo de produto proporcional à carga real, sem sobredosagem sistemática."),
   ("Estação com operação acompanhada", "Monitoramento em nível operacional e químico, não apenas fornecimento de produto."),
 ],
 "faq": [
   ("Qual a diferença entre coagulação e floculação?",
    "São duas etapas consecutivas. A coagulação neutraliza a carga elétrica das partículas coloidais, que naturalmente se repelem, permitindo que elas se aproximem — exige mistura rápida e é sensível ao pH. A floculação, em seguida, usa polímeros de cadeia longa que fazem pontes entre essas partículas já desestabilizadas, formando flocos grandes e densos o suficiente para sedimentar — exige mistura lenta. Errar a ordem, o pH ou a intensidade de mistura compromete o resultado mesmo com o produto certo."),
   ("Por que fazer jar test antes de definir o produto?",
    "Porque cada efluente responde de forma diferente. O ensaio de bancada reproduz em escala reduzida a coagulação, a floculação e a sedimentação, e permite comparar produtos, dosagens e faixas de pH antes de aplicar na estação. É a forma mais barata de evitar tanto o subdimensionamento quanto a sobredosagem."),
   ("A Scherr acompanha a operação da estação ou só fornece produto?",
    "Acompanhamos a operação. O monitoramento das estações de efluentes é feito em nível operacional e químico, com relatórios periódicos de avaliação e inspeções com registros fotográficos e filmagens. Também dispomos de laboratório químico próprio para as análises."),
   ("O tratamento de efluentes permite reuso da água?",
    "Depende do efluente e do uso pretendido. O tratamento físico-químico é a etapa que remove sólidos, cor e boa parte da carga; a viabilidade do reuso depende do que resta em solução e do requisito de qualidade do ponto de consumo. Avaliamos essa possibilidade caso a caso, inclusive integrando com o circuito de resfriamento quando faz sentido."),
 ],
},
{
 "slug": "tratamento-de-agua-gelada",
 "frase": "tratamento de água gelada",
 "icon": "snowflake",
 "nav": "Água gelada",
 "title": "Tratamento de Água Gelada e Circuitos de Chiller | Scherr",
 "desc": "Produtos químicos e assistência técnica para circuitos fechados de água gelada, chillers e fancoils: controle de corrosão, incrustação e microbiologia.",
 "h1": "Tratamento de água gelada e circuitos fechados",
 "lead": "Programas químicos para circuitos fechados de água gelada, chillers e fancoils. Volume de reposição baixo não significa ausência de risco: é justamente no circuito fechado mal tratado que a corrosão passa despercebida até obstruir o sistema.",
 "service_name": "Tratamento de água gelada e sistemas de resfriamento",
 "img": "partners-water-drop.jpg",
 "img_alt": "Superfície de água limpa em circuito de resfriamento",
 "problem_h2": "O risco específico dos circuitos fechados",
 "problem_p": "Um circuito fechado troca pouca água, e por isso é comum tratá-lo como se não precisasse de programa químico. Na prática, ele acumula os produtos da própria degradação: sem reposição significativa, tudo o que corrói fica dentro do sistema.",
 "problem_items": [
   ("Corrosão de baixa taxa e efeito cumulativo", "A taxa de corrosão é baixa, mas os produtos de corrosão não são removidos por purga. Ao longo dos anos eles se acumulam, obstruem fancoils e trocadores de placas e reduzem a vazão."),
   ("Corrosão galvânica", "Circuitos com aço carbono, cobre e alumínio no mesmo loop favorecem o par galvânico, com ataque concentrado no metal menos nobre."),
   ("Contaminação microbiológica", "Bactérias redutoras de sulfato e formadoras de lodo se desenvolvem em pontos de baixa velocidade e provocam corrosão localizada sob depósito."),
   ("Perda de eficiência do chiller", "Depósito e biofilme nas superfícies de troca elevam o consumo de energia do chiller para entregar a mesma capacidade de refrigeração."),
 ],
 "how_h2": "Como estruturamos o tratamento",
 "how_items": [
   ("Limpeza e passivação inicial", "Circuitos com histórico de depósito ou de corrosão passam por limpeza química antes da entrada do programa, para que o inibidor atue sobre metal limpo."),
   ("Programa de inibição multimetal", "Seleção de inibidores compatíveis com todos os metais presentes no loop, protegendo simultaneamente aço, cobre e ligas."),
   ("Controle microbiológico do circuito fechado", "Programa dimensionado para o baixo volume de reposição, com contagem microbiológica periódica."),
   ("Monitoramento e reposição controlada", "Acompanhamento da concentração do inibidor — a diluição por reposição não controlada é a causa mais comum de falha em circuito fechado."),
 ],
 "prod_h2": "Linha de produtos aplicada em circuitos fechados",
 "prod_items": [
   "Inibidores de corrosão multimetal para aço, cobre e ligas",
   "Produtos para controle de pH e alcalinidade do circuito",
   "Biocidas para controle microbiológico em baixo volume de reposição",
   "Dispersantes para remoção de produtos de corrosão em suspensão",
   "Produtos para limpeza química de pré-operação de sistemas de fancoil e chiller",
   "Aditivos para proteção de sistemas em parada prolongada",
 ],
 "results_items": [
   ("Consumo de energia preservado", "Superfícies de troca limpas mantêm o COP do chiller próximo ao de projeto."),
   ("Fancoils e trocadores desobstruídos", "Menos produtos de corrosão circulando, menos entupimento em trocadores de placas."),
   ("Vida útil do circuito", "Proteção simultânea dos diferentes metais presentes no loop."),
   ("Controle documentado", "Análises periódicas de concentração de inibidor e contagem microbiológica."),
 ],
 "faq": [
   ("Circuito fechado realmente precisa de tratamento químico?",
    "Precisa. A ideia de que circuito fechado não corrói vem de observar a taxa instantânea, que de fato é baixa. O problema é o acúmulo: como praticamente não há purga, todo produto de corrosão gerado permanece no sistema e vai se depositar em trocadores de placas e fancoils, que são os componentes de menor passagem. Muitos casos de perda de vazão em sistemas de água gelada têm essa origem."),
   ("Por que a reposição de água é um ponto crítico?",
    "Porque cada reposição dilui o inibidor. Um circuito com vazamento crônico consome inibidor continuamente e, sem monitoramento, opera boa parte do tempo abaixo da concentração de proteção — que é a pior condição possível, já que concentrações insuficientes de alguns inibidores podem agravar a corrosão localizada em vez de contê-la. Por isso monitoramos a concentração, não apenas dosamos."),
   ("O que fazer com o sistema em parada prolongada?",
    "Sistemas parados exigem cuidado específico: água estagnada, sem circulação e sem renovação de inibidor, favorece corrosão e crescimento microbiológico. Existem aditivos e procedimentos de preservação para esse período. Vale definir isso antes da parada, não depois."),
   ("Vocês fazem limpeza química de fancoil e chiller?",
    "Sim. Executamos limpezas químicas em sistemas de compressores (fancoil), trocadores de calor, tubulações em geral, bombas, equipamentos e tanques."),
 ],
},
{
 "slug": "abrandadores-e-desmineralizadores",
 "frase": "abrandamento e desmineralização de água",
 "icon": "flask-conical",
 "nav": "Abrandadores",
 "title": "Abrandadores, Desmineralizadores e Água de Alta Pureza | Scherr",
 "desc": "Produtos e suporte técnico para sistemas de abrandamento, desmineralização por troca iônica e geração de água de alta pureza para processo industrial.",
 "h1": "Abrandadores, desmineralizadores e água de alta pureza",
 "lead": "Produtos e suporte técnico para sistemas de abrandamento, desmineralização por troca iônica e geração de água de alta pureza — a etapa de tratamento externo que define a qualidade da água que entra na caldeira e no processo.",
 "service_name": "Abrandadores, desmineralizadores e água de alta pureza",
 "img": "services-lab-testing.jpg",
 "img_alt": "Amostras de água em análise de qualidade no laboratório",
 "problem_h2": "Por que o tratamento externo determina o custo do tratamento interno",
 "problem_p": "Toda dureza, sílica e matéria orgânica que passa pelo tratamento externo vira problema — e custo de produto químico — no tratamento interno da caldeira ou no processo. Um abrandador com resina exaurida ou uma regeneração mal conduzida transferem silenciosamente essa carga para a frente.",
 "problem_items": [
   ("Vazamento de dureza", "Resina exaurida, saturada ou com regeneração insuficiente deixa passar cálcio e magnésio, que precipitam onde o sistema é mais quente."),
   ("Perda de capacidade da resina", "Incrustação, fouling orgânico, contaminação por ferro e ataque por cloro livre reduzem progressivamente a capacidade de troca e encurtam o ciclo."),
   ("Regeneração ineficiente", "Concentração, vazão e tempo de contato do regenerante fora de faixa consomem sal ou ácido e álcali em excesso e entregam menos capacidade."),
   ("Sílica no vapor", "Em caldeiras de pressão mais alta, a sílica não removida volatiliza e se deposita nas palhetas da turbina — um problema que só o tratamento externo resolve."),
 ],
 "how_h2": "Como estruturamos o atendimento",
 "how_items": [
   ("Análise da água bruta e definição da rota", "A qualidade da água disponível e o requisito do ponto de consumo definem se a rota é abrandamento, desmineralização por leito duplo ou leito misto, ou combinação com membranas."),
   ("Avaliação da resina e do ciclo", "Verificação de capacidade, do perfil de exaustão e das condições de regeneração, para identificar se a perda de desempenho é de resina, de operação ou de água bruta."),
   ("Produtos para preservação e recuperação de resina", "Limpeza de fouling orgânico, remoção de ferro e produtos de preservação para períodos de parada."),
   ("Controle analítico do produto final", "Acompanhamento de dureza, condutividade e sílica na saída, com laboratório químico próprio."),
 ],
 "prod_h2": "Produtos e suporte para sistemas de troca iônica",
 "prod_items": [
   "Produtos para limpeza química de resinas com fouling orgânico",
   "Produtos para remoção de ferro e de contaminantes metálicos em resina",
   "Produtos de preservação de resina para paradas prolongadas",
   "Sequestrantes e antiincrustantes para proteção de membranas",
   "Produtos para correção de pH e condicionamento de água desmineralizada",
   "Suporte técnico para dimensionamento de regeneração e ciclo",
 ],
 "results_items": [
   ("Água de alimentação dentro da especificação", "Dureza e sílica controladas na entrada da caldeira ou do processo."),
   ("Ciclo de regeneração otimizado", "Consumo de regenerante proporcional à capacidade efetivamente entregue."),
   ("Vida útil da resina", "Limpeza e preservação evitam a substituição precoce do leito."),
   ("Menos carga para o tratamento interno", "Água externa bem tratada reduz a demanda de produto químico dentro da caldeira."),
 ],
 "faq": [
   ("Qual a diferença entre abrandamento e desmineralização?",
    "O abrandamento troca os íons de dureza — cálcio e magnésio — por sódio, usando resina catiônica regenerada com salmoura. Ele remove a dureza, mas mantém os sólidos dissolvidos totais praticamente inalterados. A desmineralização remove cátions e ânions, entregando água de condutividade muito baixa, e usa resinas catiônica e aniônica regeneradas com ácido e álcali. A escolha depende da pressão da caldeira e do requisito do processo: abrandamento costuma bastar em baixa pressão; pressões mais altas e processos sensíveis exigem desmineralização."),
   ("O que reduz a vida útil da resina de troca iônica?",
    "Principalmente quatro fatores: fouling orgânico da água bruta, que bloqueia os sítios ativos; contaminação por ferro e manganês; ataque oxidativo por cloro livre, que quebra a estrutura da resina de forma irreversível; e regenerações mal conduzidas. Os três primeiros podem ser tratados com limpeza química específica se identificados a tempo — o quarto é irreversível."),
   ("Como sei que meu abrandador está deixando passar dureza?",
    "Pelo controle analítico na saída. Um aumento de dureza residual antes do fim do ciclo previsto indica perda de capacidade — que pode ser exaustão, fouling ou canalização no leito. É por isso que a análise de saída precisa ser rotina, e não apenas verificação eventual: o sintoma na caldeira aparece semanas depois, já na forma de depósito."),
   ("Vocês montam laboratório na planta do cliente?",
    "Sim. Realizamos a montagem de laboratório com toda a infraestrutura, aparelhagem em geral e analista, além de dispormos de laboratório químico próprio para as análises."),
 ],
},
{
 "slug": "tratamento-de-oleo-combustivel",
 "frase": "tratamento de óleo combustível",
 "icon": "fuel",
 "nav": "Óleo combustível",
 "title": "Tratamento de Óleo Combustível | Aditivos Químicos | Scherr",
 "desc": "Linha completa de aditivos para tratamento de óleo combustível, com equipe técnica para indicar o produto adequado a cada aplicação e tipo de queimador.",
 "h1": "Tratamento de óleo combustível",
 "lead": "Linha completa de aditivos para tratamento de óleo combustível, com equipe técnica preparada para indicar o produto adequado a cada caso — combustão, estocagem, borra e proteção das superfícies do lado dos gases.",
 "service_name": "Tratamento de óleo e combustível",
 "img": "about-industrial-valves.jpg",
 "img_alt": "Válvulas e tubulação de sistema industrial de combustível",
 "problem_h2": "O que o combustível não tratado custa à operação",
 "problem_p": "Óleo combustível pesado é um produto instável ao longo do tempo e sensível à temperatura. Os problemas aparecem em dois lugares distintos: no tanque, antes da queima, e nas superfícies de troca, depois dela.",
 "problem_items": [
   ("Borra e sedimentação no tanque", "A separação de asfaltenos e a acumulação de água formam borra no fundo do tanque, que reduz o volume útil, entope filtros e exige limpeza."),
   ("Combustão incompleta", "Atomização deficiente e queima incompleta geram fuligem, elevam o consumo específico e aumentam a emissão de material particulado."),
   ("Depósito no lado dos gases", "Fuligem e cinzas depositam-se nos tubos e nas superfícies de troca, reduzindo a eficiência da caldeira e exigindo sopragem mais frequente."),
   ("Corrosão por baixa temperatura", "Enxofre no combustível forma ácido sulfúrico quando os gases resfriam abaixo do ponto de orvalho ácido, atacando pré-aquecedores, dutos e chaminé."),
 ],
 "how_h2": "Como estruturamos o atendimento",
 "how_items": [
   ("Caracterização do combustível e do sistema", "Levantamento do tipo de óleo, das condições de estocagem e aquecimento, do queimador e do histórico de depósito e de limpeza."),
   ("Seleção do aditivo", "Definição do produto conforme o objetivo predominante — dispersão de borra, melhoria de combustão, controle de depósito no lado dos gases ou proteção contra corrosão ácida."),
   ("Definição do ponto e da taxa de dosagem", "O ponto de aplicação e a taxa determinam boa parte do resultado, especialmente para aditivos de combustão."),
   ("Acompanhamento de resultado", "Inspeções com registros fotográficos e filmagens e relatórios periódicos de avaliação do tratamento."),
 ],
 "prod_h2": "Linha de aditivos para óleo combustível",
 "prod_items": [
   "Dispersantes de borra e estabilizantes para tanques de estocagem",
   "Aditivos de combustão para melhoria de queima e redução de fuligem",
   "Produtos para controle de depósito no lado dos gases",
   "Aditivos para elevação do ponto de fusão de cinzas",
   "Produtos para proteção contra corrosão por baixa temperatura",
   "Desemulsificantes e produtos para remoção de água",
 ],
 "results_items": [
   ("Consumo específico menor", "Queima mais completa entrega mais calor útil por unidade de combustível."),
   ("Menos parada para limpeza", "Controle de depósito no lado dos gases reduz a frequência de intervenção."),
   ("Tanque com volume útil preservado", "Dispersão de borra evita a perda progressiva de capacidade de estocagem."),
   ("Proteção de dutos e pré-aquecedores", "Redução do ataque ácido nas regiões de temperatura mais baixa."),
 ],
 "faq": [
   ("O que é borra de óleo combustível e como evitá-la?",
    "Borra é o material que se separa do óleo no tanque: asfaltenos que floculam por instabilidade ou incompatibilidade entre partidas diferentes de combustível, somados a água e sedimentos. Ela se acumula no fundo, reduz o volume útil do tanque, entope filtros e prejudica a atomização. Aditivos dispersantes mantêm esse material em suspensão fina, o que evita a formação da camada consolidada — e é bem mais barato do que remover borra já depositada."),
   ("Aditivo de combustão realmente reduz consumo?",
    "O ganho vem de queima mais completa: melhor atomização e menos carbono não queimado significam mais calor útil por unidade de combustível, além de menos fuligem depositada nas superfícies de troca — e superfície limpa transfere mais calor. A magnitude do ganho depende do estado atual do sistema: uma operação já bem ajustada tem menos margem do que uma com histórico de fuligem e depósito. Por isso avaliamos o caso antes de indicar o produto."),
   ("O que é corrosão por ponto de orvalho ácido?",
    "O enxofre do combustível forma SO₂ e SO₃ na queima. Quando os gases resfriam abaixo do ponto de orvalho ácido, o SO₃ combina com o vapor d'água e condensa como ácido sulfúrico sobre o metal — tipicamente em pré-aquecedores de ar, dutos e chaminé, que são as regiões mais frias. É a razão pela qual não se opera a temperatura de saída dos gases arbitrariamente baixa só para ganhar eficiência."),
   ("Como escolher o aditivo certo para o meu caso?",
    "Depende do problema predominante, do tipo de óleo e do sistema de queima. Nossa equipe técnica avalia o caso e indica o produto adequado — a linha cobre desde tratamento de tanque até controle de depósito e proteção contra corrosão ácida."),
 ],
},
]
